CREATE TABLE IF NOT EXISTS `sys_message` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_user` varchar(255) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `update_user` varchar(255) DEFAULT NULL,
  `is_delete` char(1) DEFAULT NULL,
  `title` varchar(100) DEFAULT NULL,
  `content` text,
  `message_type` varchar(20) DEFAULT NULL,
  `source_type` varchar(50) DEFAULT NULL,
  `source_id` varchar(50) DEFAULT NULL,
  `receiver_id` varchar(50) DEFAULT NULL,
  `sender_id` varchar(50) DEFAULT NULL,
  `is_read` char(1) DEFAULT '0',
  `read_time` datetime DEFAULT NULL,
  `channel` varchar(20) DEFAULT 'system',
  `link_type` varchar(20) DEFAULT 'route',
  `link_url` varchar(200) DEFAULT NULL,
  `link_params` json DEFAULT NULL,
  `extra_data` json DEFAULT NULL,
  `is_active` char(1) DEFAULT '1',
  PRIMARY KEY (`id`)
);
